### ISSUE TITLE
Repository is incompatible with WoWUp

### ISSUE THREAD

**Issue by KevinTyrrell** [denishamann/ArenaStatsTBC#10]
Installing ArenaStatsTBC for TBC using WoWUp by inputting the URL of this repository yields the following error:

![image](https://user-images.githubusercontent.com/12791400/168792849-fc94b9b0-5fbf-47d1-a982-c48e7f73a1c3.png)

Given the popularity of WoWUp and the lack of Curseforge as an option, it is highly recommended you make this repository compatible with WoWUp in order to allow ease-of-use when installing. Otherwise the only option given to users is manually updating, which is not ideal.

**Comment by denishamann** [comment]
Hello VekinTyrrel,

Thanks for reporting the issue.

I was using Curseforge's Automatic Packaging.
I fixed the issue manually.
For now I will need to manually add the well formed .zip file each time I publish a new release until I take the time to setup a proper CD (GitHub actions). I'm also waiting a bit to see how things are evolving between WowUp and Curseforge.

Kr,

Denis

**Comment by KevinTyrrell** [comment]
Thank you. I know manually uploading releases is a pain but it will be worth it for your userbase. People are abandoning curseforge en'masse due to them forcing users to use Overwolf bloatware. All addons being re-uploaded to either GitHub or WoWInterface seems to be the current best option.
