### ISSUE TITLE
Suggestion: Presort Opponent Classes Instead of Arena1/2/3

### ISSUE THREAD

**Issue by bluedreamz1** [denishamann/ArenaStatsTBC#3]
Instead of storing opponent classes per Arena1/2/3, use some type of sorting so that classes appear in a consistent order.  This would make the addon much more readable and make the data easier to work with.

e.g.

Rogue mage priest could appear

RMP
PMR
MPR
MRP
RPM

**Comment by denishamann** [comment]
Hello, thanks for this feature request.
It has been implemented in this PR:
https://github.com/denishamann/ArenaStatsTBC/pull/4
And is available from version 0.1.0 of the addon
