### ISSUE TITLE
matchups often are failing to correctly record

### ISSUE THREAD

**Issue by JulianNorton** [denishamann/ArenaStatsTBC#5]
when leaving a game, it will combine matches instead of correctly separating out.
![image](https://user-images.githubusercontent.com/2412992/158040126-395a1051-f02d-4677-8fe1-50d59efff203.png)
this makes the data useless

**Comment by denishamann** [comment]
Hello JulianNorton,
Thanks for this issue report.
Version 0.1.0 of the addon should fix this issue.
Can you confirm on your end?

**Comment by JulianNorton** [comment]
Are there ways to download this that aren't on curse?

**Comment by JulianNorton** [comment]
Yes, Thank you @denishamann ! I figured out wowup.io wasn't automatically updated (I assume because of Curse?) I had to manually update the files to update it.

**Comment by denishamann** [comment]
Thanks for the answer.
I use wowup and it's fine for me (and other testers too) 
Don't hesitate to reach me in case you still have troubles.
