### ISSUE TITLE
can not open the main window

### ISSUE THREAD

**Issue by Saiyoulol** [denishamann/ArenaStatsTBC#6]
the lastest version (0.1.0) can not open the window （the verion 0.0.1 works fine）
whatever use the button or console (/arenastats) or disable all the other adds.

**Comment by denishamann** [comment]
Hello Saiyoulol. Maybe you were a rare case of upgrading from 0.0.1 directly to 0.1.0.
I will try to reproduce.
If in the meantime you could enable the script errors and paste it here it would help me a lot.
You can do this by typing: 

/console scriptErrors 1

To set it back to disabled you can do:

/console scriptErrors 0

Thanks!

**Comment by Saiyoulol** [comment]
Message: Interface\AddOns\ArenaStatsTBC\GUI.lua:374: attempt to concatenate local 'id' (a nil value)
Time: Thu Mar 24 04:56:58 2022
Count: 2
Stack: Interface\AddOns\ArenaStatsTBC\GUI.lua:374: attempt to concatenate local 'id' (a nil value)
[string "@Interface\AddOns\ArenaStatsTBC\GUI.lua"]:374: in function `GetShortMapName'
[string "@Interface\AddOns\ArenaStatsTBC\GUI.lua"]:232: in function `RefreshLayout'
[string "@Interface\AddOns\ArenaStatsTBC\GUI.lua"]:298: in function `Show'
[string "@Interface\AddOns\ArenaStatsTBC\GUI.lua"]:308: in function `Toggle'
[string "@Interface\AddOns\ArenaStatsTBC\ArenaStats.lua"]:206: in function `OnClick'
[string "@Interface\AddOns\ArenaStatsTBC\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua"]:144: in function <...s\ArenaStatsTBC\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:142>

Locals: self = <table> {
 BuildTable = <function> defined @Interface\AddOns\ArenaStatsTBC\ArenaStats.lua:241
 EnableModule = <function> defined @Interface\AddOns\ArenaStatsTBC\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 baseName = "ArenaStatsTBC"
 IterateEmbeds = <function> defined @Interface\AddOns\ArenaStatsTBC\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 UpdateTableView = <function> defined @Interface\AddOns\ArenaStatsTBC\GUI.lua:166
 Printf = <function> defined @Interface\AddOns\ArenaStatsTBC\Libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\ArenaStatsTBC\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 Show = <function> defined @Interface\AddOns\ArenaStatsTBC\GUI.lua:292
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\ArenaStatsTBC\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 UPDATE_BATTLEFIELD_SCORE = <function> defined @Interface\AddOns\ArenaStatsTBC\ArenaStats.lua:159
 DisableModule = <function> defined @Interface\AddOns\ArenaStatsTBC\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 SetLastArenaRankingData = <function> defined @Interface\AddOns\ArenaStatsTBC\ArenaStats.lua:59
 CalculateTeamSize = <function> defined @Interface\AddOns\ArenaStatsTBC\ArenaStats.lua:231
 RegisterMessage = <function> defined @Interface\AddOns\ArenaStatsTBC\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\ArenaStatsTBC\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 ResetDatabase = <function> defined @Interface\AddOns\ArenaStatsTBC\ArenaStats.lua:353
 mapListShortName = <table> {
 }
 arenaEnded = false
 CreateShortMapName = <function> defined @Interface\AddOns\ArenaStatsTBC\GUI.lua:42
 SetEnabledState = <function> defined @Interface\AddOns\ArenaStatsTBC\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 ZONE_CHANGED_NEW_AREA = <function> defined @Interface\AddOns\ArenaStatsTBC\ArenaStats.lua:39
 RegisterEvent = <function> defined @Interface\AddOns\ArenaStatsTBC\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 ExportEditBox = <function> defined @Interface\AddOns\ArenaStatsTBC\GUI.lua:379
 DrawMinimapIcon = <function> defined @Interface\AddOns\ArenaStatsTBC\ArenaStats.lua:194
 IterateModules = <function> defined @Interface\AddOns\ArenaStatsTBC\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
 UPDATE_BATTLEFIELD_STATUS = <function> defined @Interface\AddOns\ArenaStatsTBC\ArenaStats.lua:44
 ClassIconId = <function> defined @Interface\AddOns\ArenaStatsTBC\GUI.lua:322
 Enable = <function> defined @Interface\AddOns\ArenaStatsTBC\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Interface\AddOns\ArenaStatsTBC\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetModule = <function> defined @Interface\AddOns\ArenaStatsTBC\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 ExportFrame = <function> defined @Interface\AddOns\ArenaStatsTBC\GUI.lua:378
 defaultModuleLibraries = <table> {
 }
 ComputeSafeNumber = <function> defined @Interface\AddOns\ArenaStatsTBC\ArenaStats.lua:483
 CreateGUI = <function> defined @Interface\AddOns\ArenaStatsTBC\GUI.lua:57
 UnregisterChatCommand = <function> defined @Interface\AddOns\Are

**Comment by Saiyoulol** [comment]
Thanks for your respon.
Here are the script error code.

**Comment by denishamann** [comment]
The issue seems indeed to be related with the CN language.
It's working in for other languages than EN (I tested FR) but I guess it's not working because of the special characters encoding.
Unfortunately I tried to switch my language to CN for testing but I discovered that it's not possible to login on a EU server when your client is in CN...
I tried to "blindly" pushed a temporary fix for the issue (available in version 0.1.1). There is a chance that it shows "E" as map name for old data. But the rest of the addon should work fine.
Please keep me posted if it solves your issue or if there is any other "language" issue.

Thank you

**Comment by Saiyoulol** [comment]
HOLLY GOD
IT'S FIXED

**Comment by Saiyoulol** [comment]
THANK YOU SOOOOOOO MUCH

**Comment by denishamann** [comment]
You are welcome! Enjoy your arenas

**Comment by Saiyoulol** [comment]
Could u fix more problem pls ? ( It might be my own problem haha )

1,When i use my customized Fonts, the MMR number are very hard to read.
just like the this : https://imgur.com/a/uA9UEFk

2,And due to the language problem.
the map name are always be "e" , the Facion are always be "horde". 
Can i do something for you to fix this CN language problem?

3,Last but not least, the main window can only check my last 15 records.
if there is a chance that could make it to 25 or 30?

**Comment by Saiyoulol** [comment]
I'm sorry to trouble you a lot. But these are really bothers me.
i m a streamer and the vivewers' are alaways ask me about why the enemys' are horde all night.

**Comment by denishamann** [comment]
1. Were the numbers correctly displayed before the update? Is it Elvui? Can you give me the font you are using? I will try it but it seems that I just need to make the column a little bit larger. 

2. It is indeed linked to the update and the language support. I have to dig for this one (and also the map names) but these are not easy fix + it's not easy for me to test. Maybe I will reach you if I need to test a version before deploying it.

3. I'm not sure to understand. Can't you scroll? Or you want to be able to see more games at once without scrolling? 

I will try to address those problems as fast as possible.

**Comment by Saiyoulol** [comment]
1, version 0.0.1 are also can't display correct. It's called NDUI base on Elvui.
 I think is just need to make the column a little bit larger will fix this problem. 
2, it seems version 0.1.1 are fix the map name problem (it display a single First Chinese letter）
3,yeah, i want to see more games at once without scrolling,
and I add "asGui.f:SetHeight(1000)" in GUI.lua,it just display the way i want :)

**Comment by Saiyoulol** [comment]
and thanks for the reply
you are the best :)

**Comment by denishamann** [comment]
1. I will push something soon for larger columns.
2. Yeaaah! Hope it's a stable solution (and sorry it isn't fully working for old data)
3. Yes just do that. Maybe one day I will make the window resizable but it's not on my priority list. Don't forget to change this line everytime there is an update.
